{% set version = environ.get("ST_VERSION", "0.2.2") %}

package:
  name: sqtop
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}

test:
  commands:
    - sqtop --help

about:
  home: https://github.com/Wubeizhongxinghua/s-top
  summary: Interactive terminal monitor for Slurm clusters
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/Wubeizhongxinghua/s-top

extra:
  recipe-maintainers:
    - Wubeizhongxinghua
